### ISSUE TITLE
wiring into existing spring-boot app fails: "No property findAll found for type..."

### ISSUE THREAD

**Issue by tomcgn** [darrachequesne/spring-data-jpa-datatables#1]
Hello Damien, 
spring-data-jpa-datatables is just what I was looking for. I was about to implement a direct connector between datatables and a spring rest repository, when I found it. 
I could run the example project and it works just fine. I'll post an enhancement for easier testing (CORS Headers) later on. 
I'd like to integrate your approach into an existing app. I added the dependency and the annotation

`@EnableJpaRepositories(repositoryFactoryBeanClass = DataTablesRepositoryFactoryBean.class)`
to the Application class. 

When I start the application, an exception is thrown: 
org.springframework.data.mapping.PropertyReferenceException: No property findAll found for type Meeting...

In the Interface `@Repository public interface MeetingRepository extends PagingAndSortingRepository<Meeting, Long> ` several method signatures exist, and I added a `DataTablesOutput<Meeting> findAll(DataTablesInput input);`

The app uses Spring Boot Starter 1.2.4 . 
Any ideas why the discovery of the repository methods fails?

**Comment by darrachequesne** [comment]
Hi! Glad you find it useful! Don't hesitate if you find something is missing.

My first guess is that your `MeetingRepository` should extend `DataTablesRepository` (which itself extends `PagingAndSortingRepository`). The findAll method is defined there https://github.com/darrachequesne/spring-data-jpa-datatables/blob/master/src/main/java/org/springframework/data/jpa/datatables/repository/DataTablesRepository.java#29

Cheers

**Comment by tomcgn** [comment]
Hi Damien, 
Thanks for the quick response. And for the very good work! 

Sure, I didn't miss the inheritance so the reason was something else. 

The autowiring of the existing repositories failed, if the application is configured to use `@EnableJpaRepositories(repositoryFactoryBeanClass = DataTablesRepositoryFactoryBean.class)` for all repos.
The solution is to create new repos that extend the exisiting ones, in a distinct package - anyways a good idea to keep existing api stable, and have these repositories interfaces extend the `DataTablesRespository`, as you suggest. 

Then, you can specify that package in `Application.java` `@EnableJpaRepositories(repositoryFactoryBeanClass = DataTablesRepositoryFactoryBean.class, basePackages = "org.whatever.repository.datatables")`
Then the differing factory is only applied to the repositories responsible for datatables. 

Sorting and paging works fine now. 
I will continue tomorrow with the search, which does not yet work. 

Thanks again for sharing this, it was definitely missing and is worth a mention on [datatables.net](http://datatables.net/development/server-side/)

**Comment by darrachequesne** [comment]
Well, it seems my answer was, if quick, not really useful :smile: 

Your solution is great, I think it's worth a mention in the readme! You could also create your own RepositoryFactory (disclaimer: your solution is cleaner):
```java
private static class YourCustomRepositoryFactory<T, ID extends Serializable>
			extends JpaRepositoryFactory {
		[...]

		@SuppressWarnings({ "unchecked" })
		protected Object getTargetRepository(RepositoryMetadata metadata) {
			JpaEntityInformation<T, Serializable> entityInformation = (JpaEntityInformation<T, Serializable>) getEntityInformation(metadata
					.getDomainType());
			Class<?> repositoryInterface = metadata.getRepositoryInterface();

			return DataTablesRepository.class.isAssignableFrom(repositoryInterface)
					? new DataTablesRepositoryImpl<T, ID>(entityInformation, entityManager)
					: <your other implementation here>;
		}
	}
``` 

PS: search should be working, maybe some column must be set with `searchable: false` on the client-side (yet another clueless guess!). 

Cheers

**Comment by tomcgn** [comment]
Well, your last one was, if only I followed your advice:
Live seach works as intended if disable searching on all except one coiumn!
That will do for the moment, thanks again :)
I will leave the [other issue open](https://github.com/darrachequesne/spring-data-jpa-datatables/issues/2), as it adresses a slightly different topic (search on all filed of an entitiy rather than on one column/member of the model class.
Cheers

**Comment by shubham-aggarwal** [comment]
Just specifying `repositoryFactoryBeanClass = DataTablesRepositoryFactoryBean.class` in my `Application` class did the trick.

**Comment by jamesavilla** [comment]
Im getting an error when trying to use this plugin and haven't had any luck getting it working.  I'm running org.springframework.boot 1.5.4.RELEASE

java.lang.NoSuchMethodError: org.springframework.data.jpa.domain.Specification.where(Lorg/springframework/data/jpa/domain/Specification;)Lorg/springframework/data/jpa/domain/Specification;
	at org.springframework.data.jpa.datatables.repository.DataTablesRepositoryImpl.findAll(DataTablesRepositoryImpl.java:67) ~[spring-data-jpa-datatables-5.0.0.jar:?]
	at org.springframework.data.jpa.datatables.repository.DataTablesRepositoryImpl.findAll(DataTablesRepositoryImpl.java:27) ~[spring-data-jpa-datatables-5.0.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:504) ~[spring-data-commons-1.13.4.RELEASE.jar:?]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:489) ~[spring-data-commons-1.13.4.RELEASE.jar:?]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:461) ~[spring-data-commons-1.13.4.RELEASE.jar:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:56) ~[spring-data-commons-1.13.4.RELEASE.jar:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133) ~[spring-data-jpa-1.11.4.RELEASE.jar:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57) ~[spring-data-commons-1.13.4.RELEASE.jar:?]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at com.sun.proxy.$Proxy102.findAll(Unknown Source) ~[?:?]
	at com.scapharm.web.restcontroller.UserRestController.list(UserRestController.java:30) ~[classes/:?]
